FROM ollama/ollama

# Copiez le script dans l'image
COPY ./ollama/pull-model.sh /pull-model.sh

# Assurez-vous que le script est exécutable
RUN chmod +x /pull-model.sh

# Exécution du script directement, sans besoin de shell
ENTRYPOINT ["/pull-model.sh"]
