# Utilise une image Python légère
FROM python:3.12-slim

# Configure l'environnement de travail
WORKDIR /app

# Copie les fichiers nécessaires
COPY ./fastapi /app

# Installe les dépendances
RUN pip install --no-cache-dir fastapi uvicorn requests jinja2 python-multipart

# Expose le port utilisé par FastAPI
EXPOSE 8000

# Commande pour lancer l'application
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
